baseURL = "https://gerkovink.github.io"
languageCode = "en-us"
title = "Gerko Vink"
theme = "coder" # Set the theme.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

#disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Gerko Vink" # Author's name.
    info = "dark data scientist" # Author's job title or info.
    description = "" # Site description.
    keywords = "Gerko Vink, Gerko, Vink, Developer, Statistician" # Site keywords.
    avatarurl = "images/gerko_cartoon.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "occasional Bayesian | incidental frequentist | properly uncertain" # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/gerkovink"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://nl.linkedin.com/in/gerko-vink-670b4017"
[[params.social]]
    name = "UU"
    weight = 2
    url = "https://www.uu.nl/staff/GVink/0"
[[params.social]]
    name = "Mail me"
    weight = 3
    url = "mailto:G.Vink@uu.nl"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/OkregK"

# Menu links
[[menu.main]]
    name = "About me"
    weight = 1
    url  = "/abt/"
[[menu.main]]
    name = "Courses"
    weight = 2
    url = "/crs/"
[[menu.main]]
    name = "CV"
    weight = 2
    url = "/cv/Vink.pdf"
[[menu.main]]
    name = "Development"
    weight = 2
    url = "/dvlp/"
[[menu.main]]
    name = "Consultation"
    weight = 2
    url = "/cnslt/"
[[menu.main]]
    name = "Research"
    weight = 2
    url = "/pubs/"
